name: bwu_grinder_tasks
version: 0.1.1-dev.3
description: A collection of common grinder tasks to reuse in different projects.
homepage: https://github.com/bwu-dart/bwu_grinder_tasks
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  grinder: ^0.8.0

dev_dependencies:
  test: ^0.12.0

dependency_overrides:

#transformers:
#- test/pub_serve:
#    $include: test/**_test{.*,}.dart

