name: bwu_grinder_tasks
version: 0.1.1-dev.6
description: A collection of common grinder tasks to reuse in different projects.
homepage: https://github.com/bwu-dart/bwu_grinder_tasks
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  grinder: ^0.8.0

dev_dependencies:
  path: '^1.4.1'
  pub_server: '^0.1.1+3'
  test: ^0.12.0
  yaml: '^2.1.12'

dependency_overrides:

#transformers:
#- test/pub_serve:
#    $include: test/**_test{.*,}.dart

