name: bwu_grinder_tasks
version: 0.2.0-dev.0
description: A collection of common grinder tasks to reuse in different projects.
homepage: https://github.com/bwu-dart/bwu_grinder_tasks
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=2.0.0-a <3.0.0'

dependencies:
  grinder: ^0.8.0
  pub_semver: '^1.3.2'
  yaml: '^2.1.12'
  path: '^1.4.1'

dev_dependencies:
  pub_server: '^0.1.1+3'
  test: ^1.3.0

dependency_overrides:

#transformers:
#- test/pub_serve:
#    $include: test/**_test{.*,}.dart

